### 판다스 사용에 보기 좋은 사이트
https://dataitgirls2.github.io/10minutes2pandas/



####판다스 사용중 모르는 함수
https://pandas.pydata.org/docs/

pandas manual -> documentation -> user guide

## [1] 판다스를 이용한 동물예측 데이터 로더

In [3]:
import numpy as np
import torch
import torch.optim as optim
import pandas as pd

torch.manual_seed(1)

! curl 'https://raw.githubusercontent.com/sejongresearch/2020.Spring.AI/master/HW/zoo_class.csv' -o 'zoo_class.csv'
print('Done..\n')

xy=np.loadtxt('zoo_class.csv',delimiter=',', dtype=np.float32)
    #numpy를 이용해 읽어오는 함수.
    #numpy를 이용해서 읽어오게되면 헤더까지 같이 읽어오게된다.
    # 그래서 pandas를 이용하기.

pandas_xy=pd.read_csv("zoo_class.csv", header=None); 
                               #헤더 none은 데이터에 따라 다르다.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3535  100  3535    0     0  15572      0 --:--:-- --:--:-- --:--:-- 15641
Done..

In [4]:
xy        #numpy로 읽어온 데이터. 분석하기 어려운 데이터

array([[1., 0., 0., ..., 0., 1., 0.],
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 3.],
       ...,
       [1., 0., 0., ..., 0., 1., 0.],
       [0., 0., 1., ..., 0., 0., 6.],
       [0., 1., 1., ..., 0., 0., 1.]], dtype=float32)

In [5]:
#pandas로 읽어온 데이터. 
# 가시성이 높음.데이터의 크기를 알 수 있다. row x columns

pandas_xy

     0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16
0     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   0
1     1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1   0
2     0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0   3
3     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1   0
4     1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   0
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
96    1   0   0   1   0   0   0   1   1   1   0   0   2   1   0   1   0
97    1   0   1   0   1   0   0   0   0   1   1   0   6   0   0   0   5
98    1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1   0
99    0   0   1   0   0   0   0   0   0   1   0   0   0   0   0   0   6
100   0   1   1   0   1   0   0   0   1   1   0   0   2   1   0   0   1

[101 rows x 17 columns]

In [6]:
# 데이터 헤더정보 확인하기   헤더=columns
    # 보통 csv로 만들어서 배포시, 헤더에 columns 정보가 있다. 하지만 이 데이터에는 없음.

pandas_xy.keys()

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16], dtype='int64')

In [7]:
pandas_xy.index  # 101 rows

RangeIndex(start=0, stop=101, step=1)

In [25]:
# 클래스 개수 확인하기

pandas_xy[16].max()
#pandas_xy.iloc[:,16].max()

#pandas_xy[16].min() 
#min=0, max=6. 0~6까지 7개의 클래스

0

In [8]:
#인덱스에 따른 row의 정보를 받아오기.

pandas_xy.iloc[0]

0     1
1     0
2     0
3     1
4     0
5     0
6     1
7     1
8     1
9     1
10    0
11    0
12    4
13    0
14    0
15    1
16    0
Name: 0, dtype: int64

In [9]:
# 헤더의 값을 가지고 cols의 정보가져오기

pandas_xy[0]

0      1
1      1
2      0
3      1
4      1
      ..
96     1
97     1
98     1
99     0
100    0
Name: 0, Length: 101, dtype: int64

In [10]:
# 구역의 값 가져오기
# loc[인덱스의 범위, 헤더의 범위]

pandas_xy.loc[0:10,0:5]

    0  1  2  3  4  5
0   1  0  0  1  0  0
1   1  0  0  1  0  0
2   0  0  1  0  0  1
3   1  0  0  1  0  0
4   1  0  0  1  0  0
5   1  0  0  1  0  0
6   1  0  0  1  0  0
7   0  0  1  0  0  1
8   0  0  1  0  0  1
9   1  0  0  1  0  0
10  1  0  0  1  0  0

In [11]:
# 예제 파싱하기

x_data=pandas_xy.loc[:,:15]
y_data=pandas_xy.loc[:,16]

x_data    #cols 0~15

     0   1   2   3   4   5   6   7   8   9   10  11  12  13  14  15
0     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
1     1   0   0   1   0   0   0   1   1   1   0   0   4   1   0   1
2     0   0   1   0   0   1   1   1   1   0   0   1   0   1   0   0
3     1   0   0   1   0   0   1   1   1   1   0   0   4   0   0   1
4     1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1
..   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ..
96    1   0   0   1   0   0   0   1   1   1   0   0   2   1   0   1
97    1   0   1   0   1   0   0   0   0   1   1   0   6   0   0   0
98    1   0   0   1   0   0   1   1   1   1   0   0   4   1   0   1
99    0   0   1   0   0   0   0   0   0   1   0   0   0   0   0   0
100   0   1   1   0   1   0   0   0   1   1   0   0   2   1   0   0

[101 rows x 16 columns]

In [12]:
y_data  # 16cols

0      0
1      0
2      3
3      0
4      0
      ..
96     0
97     5
98     0
99     6
100    1
Name: 16, Length: 101, dtype: int64

In [13]:
# 이전에 배운것을 활용하기 위해서는 numpy로 변경해야 함.

x_data=np.array(x_data)
y_data=np.array(y_data)
x_data

array([[1, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 1, 0, 0],
       ...,
       [1, 0, 0, ..., 1, 0, 1],
       [0, 0, 1, ..., 0, 0, 0],
       [0, 1, 1, ..., 1, 0, 0]])

## [1] pandas를 이용한 배추값 예측 데이터 로더

In [14]:
! curl 'https://raw.githubusercontent.com/sejongresearch/2020.Spring.AI/master/HW/cabbage_price.csv' -o 'cabbage_price.csv'

print('Done..\n')

data=pd.read_csv("cabbage_price.csv", sep=',')
xy=np.array(data,dtype=np.float32)

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 93044  100 93044    0     0   237k      0 --:--:-- --:--:-- --:--:--  236k
Done..

In [15]:
data   #헤더에 cols의 정보가 존재함.

      # year는 avgprice에 별로 영향을 미치지 않고, 튀는 값이기때문에 빼주어도 됌.

          year  avgTemp  minTemp  maxTemp  rainFall  avgPrice
0     20100101     -4.9    -11.0      0.9       0.0      2123
1     20100102     -3.1     -5.5      5.5       0.8      2123
2     20100103     -2.9     -6.9      1.4       0.0      2123
3     20100104     -1.8     -5.1      2.2       5.9      2020
4     20100105     -5.2     -8.7     -1.8       0.7      2060
...        ...      ...      ...      ...       ...       ...
2917  20171227     -3.9     -8.0      0.7       0.0      2865
2918  20171228     -1.5     -6.9      3.7       0.0      2884
2919  20171229      2.9     -2.1      8.0       0.0      2901
2920  20171230      2.9     -1.6      7.1       0.6      2901
2921  20171231      2.1     -2.0      5.8       0.4      2901

[2922 rows x 6 columns]

In [16]:
data.info()

#int형 두개. 하나는 인덱스, 하나는 y값 클래스
# 4개의 float형 컬럼만 사용하기

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2922 entries, 0 to 2921
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   year      2922 non-null   int64
 1   avgTemp   2922 non-null   float64
 2   minTemp   2922 non-null   float64
 3   maxTemp   2922 non-null   float64
 4   rainFall  2922 non-null   float64
 5   avgPrice  2922 non-null   int64
dtypes: float64(4), int64(2)
memory usage: 137.1 KB

## [2] 모델 학습

##[3] 정답 예측