In [184]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/city-commercialchange-analysis/submit.csv
/kaggle/input/city-commercialchange-analysis/test.csv
/kaggle/input/city-commercialchange-analysis/train.csv

In [185]:
import torch
import torchvision.datasets as data
import torchvision.transforms as transforms
import random

In [186]:
import numpy as np
import torch
import torch.optim as optim
import pandas as pd

xy=pd.read_csv('/kaggle/input/city-commercialchange-analysis/train.csv')
xy

,year,quarter,city,Operating months,Closing months,Operating months_Average,Closing months_Average,Commercial change
0,2016,1,11290,99,51,1.031250,1.062500,0
1,2019,4,11290,111,56,1.009091,1.037037,0
2,2015,4,11380,92,48,0.968421,1.000000,2
3,2019,4,11200,105,57,0.954545,1.055556,2
4,2014,2,11260,91,42,0.989130,0.933333,3
...,...,...,...,...,...,...,...,...
546,2017,2,11350,91,48,0.938144,0.960000,3
547,2019,4,11500,94,50,0.854545,0.925926,3
548,2016,3,11200,95,51,0.989583,1.040816,2
549,2018,1,11620,99,50,0.990000,1.000000,3
550,2014,3,11200,94,47,1.010753,1.044444,0

In [187]:
x_data=xy.iloc[:,0:7]    #0~7 col
y_data=xy.iloc[:,7]

x_data

,year,quarter,city,Operating months,Closing months,Operating months_Average,Closing months_Average
0,2016,1,11290,99,51,1.031250,1.062500
1,2019,4,11290,111,56,1.009091,1.037037
2,2015,4,11380,92,48,0.968421,1.000000
3,2019,4,11200,105,57,0.954545,1.055556
4,2014,2,11260,91,42,0.989130,0.933333
...,...,...,...,...,...,...,...
546,2017,2,11350,91,48,0.938144,0.960000
547,2019,4,11500,94,50,0.854545,0.925926
548,2016,3,11200,95,51,0.989583,1.040816
549,2018,1,11620,99,50,0.990000,1.000000
550,2014,3,11200,94,47,1.010753,1.044444

In [188]:
y_data

0      0
1      0
2      2
3      2
4      3
      ..
546    3
547    3
548    2
549    3
550    0
Name: Commercial change, Length: 551, dtype: int64

In [189]:
x_train=np.array(x_data)
y_train=np.array(y_data)

x_train=torch.FloatTensor(x_train)
y_train=torch.LongTensor(y_train)

x_train[:5]

tensor([[2.0160e+03, 1.0000e+00, 1.1290e+04, 9.9000e+01, 5.1000e+01, 1.0312e+00,
         1.0625e+00],
        [2.0190e+03, 4.0000e+00, 1.1290e+04, 1.1100e+02, 5.6000e+01, 1.0091e+00,
         1.0370e+00],
        [2.0150e+03, 4.0000e+00, 1.1380e+04, 9.2000e+01, 4.8000e+01, 9.6842e-01,
         1.0000e+00],
        [2.0190e+03, 4.0000e+00, 1.1200e+04, 1.0500e+02, 5.7000e+01, 9.5455e-01,
         1.0556e+00],
        [2.0140e+03, 2.0000e+00, 1.1260e+04, 9.1000e+01, 4.2000e+01, 9.8913e-01,
         9.3333e-01]])

In [190]:
x_train.shape

torch.Size([551, 7])

In [191]:
y_train.shape

torch.Size([551])

In [192]:
y_train

tensor([0, 0, 2, 2, 3, 3, 3, 3, 1, 3, 3, 3, 3, 3, 0, 3, 3, 3, 3, 2, 3, 0, 3, 3,
        3, 0, 0, 0, 2, 1, 0, 0, 3, 3, 3, 3, 0, 0, 0, 3, 3, 3, 0, 3, 3, 0, 0, 3,
        3, 0, 0, 3, 0, 3, 0, 0, 0, 2, 3, 1, 3, 1, 0, 0, 0, 1, 0, 0, 3, 3, 1, 3,
        0, 3, 3, 0, 0, 3, 3, 3, 3, 3, 1, 3, 3, 1, 3, 0, 3, 3, 3, 0, 3, 3, 3, 0,
        3, 0, 0, 0, 3, 3, 2, 3, 3, 3, 3, 3, 3, 3, 3, 0, 3, 1, 3, 3, 3, 0, 3, 3,
        3, 0, 2, 2, 3, 3, 0, 3, 1, 0, 2, 0, 1, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3,
        3, 0, 3, 1, 2, 3, 3, 3, 3, 3, 0, 0, 3, 3, 0, 3, 3, 3, 2, 0, 1, 3, 3, 0,
        3, 3, 3, 1, 0, 0, 3, 0, 3, 3, 3, 3, 3, 3, 0, 3, 0, 3, 3, 3, 3, 3, 3, 0,
        3, 0, 2, 3, 0, 0, 2, 3, 3, 0, 0, 3, 2, 3, 0, 0, 3, 3, 2, 2, 3, 2, 3, 3,
        3, 0, 0, 2, 0, 3, 0, 3, 3, 1, 3, 0, 3, 3, 3, 1, 0, 0, 1, 1, 0, 3, 3, 0,
        2, 2, 0, 3, 3, 3, 0, 3, 0, 0, 1, 3, 3, 0, 0, 3, 0, 0, 1, 3, 1, 1, 0, 3,
        3, 1, 2, 0, 3, 3, 3, 3, 3, 0, 3, 2, 3, 0, 3, 3, 3, 0, 0, 3, 0, 3, 3, 3,
        3, 0, 3, 3, 3, 3, 3, 3, 1, 0, 0, 3, 3, 0, 3, 3, 2, 0, 0, 3, 0, 0, 3, 1,
        3, 0, 3, 3, 3, 0, 0, 0, 0, 0, 3, 0, 0, 3, 3, 3, 1, 1, 3, 3, 0, 3, 3, 3,
        0, 3, 3, 3, 3, 0, 3, 3, 0, 0, 0, 3, 3, 2, 3, 3, 2, 3, 0, 1, 0, 0, 3, 0,
        0, 3, 1, 3, 3, 3, 3, 3, 3, 3, 2, 2, 3, 0, 3, 1, 0, 3, 3, 3, 3, 0, 1, 3,
        0, 3, 3, 3, 3, 3, 0, 3, 3, 3, 0, 2, 3, 2, 3, 1, 0, 0, 0, 3, 3, 3, 0, 3,
        3, 3, 0, 3, 3, 3, 3, 3, 3, 2, 3, 0, 3, 3, 0, 2, 0, 3, 3, 3, 3, 3, 3, 0,
        0, 3, 3, 0, 3, 3, 1, 1, 3, 2, 3, 0, 3, 0, 0, 0, 1, 3, 1, 2, 3, 3, 0, 3,
        0, 0, 2, 0, 3, 3, 2, 3, 1, 2, 0, 2, 3, 3, 0, 3, 0, 0, 3, 3, 0, 3, 2, 0,
        0, 3, 1, 3, 3, 0, 1, 0, 3, 3, 0, 0, 1, 1, 3, 3, 3, 3, 0, 0, 0, 0, 1, 3,
        3, 0, 0, 2, 3, 3, 0, 3, 3, 0, 0, 3, 3, 3, 3, 0, 0, 2, 1, 0, 1, 3, 3, 3,
        3, 3, 3, 3, 3, 3, 3, 0, 3, 3, 2, 0, 3, 3, 0, 3, 3, 3, 3, 3, 2, 3, 0])

### 3layer 
- xavier init
- Adam
- hidden layer node 개수: 512
- 학습 파라미터 설정
  - learning_rate = 0.01
  - training_epochs = 15
  - batch_size = 100
- -> Accuracy: 0.5483871102333069**

### training epoch과 hidden layer node 개수 변경
- training_epochs = 45 ~ 55
- hidden layer node 개수: 256

### -> Accuracy: 0.725806474685669

In [193]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'

random.seed(777)
torch.manual_seed(777)
if device == 'cuda':
  torch.cuda.manual_seed_all(777)

In [194]:
# 학습 파라미터 설정
learning_rate = 0.01
training_epochs = 45
batch_size = 100

In [195]:

train = torch.utils.data.TensorDataset(x_train, y_train)

In [196]:
data_loader = torch.utils.data.DataLoader(dataset=train,
                                          batch_size=batch_size,
                                          shuffle=True,
                                          drop_last=True)
#xy=train

In [197]:
# 3-Layer

linear1 = torch.nn.Linear(7,256,bias=True)
linear2 = torch.nn.Linear(256,256,bias=True)
linear3 = torch.nn.Linear(256,4,bias=True)
relu = torch.nn.ReLU()

In [198]:
# Random Init => Xavier Init
torch.nn.init.xavier_normal_(linear1.weight)
torch.nn.init.xavier_normal_(linear2.weight)
torch.nn.init.xavier_normal_(linear3.weight)

Parameter containing:
tensor([[ 0.0191,  0.0337,  0.0226,  ..., -0.0312, -0.0489, -0.0005],
        [-0.0130,  0.0307, -0.0692,  ..., -0.0873, -0.1966,  0.0183],
        [-0.0366,  0.0039, -0.0539,  ...,  0.1732, -0.0786, -0.0262],
        [-0.0586, -0.1101, -0.1071,  ..., -0.0391,  0.0904, -0.0184]],
       requires_grad=True)

In [199]:
model = torch.nn.Sequential(linear1,relu,linear2,relu,linear3).to(device)

In [200]:
# 손실함수와 최적화 함수
loss = torch.nn.CrossEntropyLoss().to(device) # softmax 내부적으로 계산
optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

In [201]:

total_batch = len(data_loader)
for epoch in range(training_epochs):
    avg_cost = 0

    for X, Y in data_loader:

        # one-hot encoding되어 있지 않음
        Y = Y.to(device)
        #%debug

        # 그래디언트 초기화
        optimizer.zero_grad()
        # Forward 계산
        hypothesis = model(X)
        # Error 계산
        cost = loss(hypothesis, Y)
        # Backparopagation
        cost.backward()
        # 가중치 갱신
        optimizer.step()

        # 평균 Error 계산
        avg_cost += cost / total_batch

    print('Epoch:', '%04d' % (epoch + 1), 'cost =', '{:.9f}'.format(avg_cost))

print('Learning finished')

Epoch: 0001 cost = 4618.148437500
Epoch: 0002 cost = 634.161987305
Epoch: 0003 cost = 403.280456543
Epoch: 0004 cost = 285.489440918
Epoch: 0005 cost = 87.098579407
Epoch: 0006 cost = 59.655479431
Epoch: 0007 cost = 46.773101807
Epoch: 0008 cost = 30.862020493
Epoch: 0009 cost = 22.525394440
Epoch: 0010 cost = 30.513532639
Epoch: 0011 cost = 21.526447296
Epoch: 0012 cost = 18.018480301
Epoch: 0013 cost = 9.530544281
Epoch: 0014 cost = 9.243144989
Epoch: 0015 cost = 6.049036026
Epoch: 0016 cost = 3.220332861
Epoch: 0017 cost = 4.500449657
Epoch: 0018 cost = 3.590252876
Epoch: 0019 cost = 2.773979187
Epoch: 0020 cost = 1.606364012
Epoch: 0021 cost = 1.535470247
Epoch: 0022 cost = 1.662477493
Epoch: 0023 cost = 1.895922899
Epoch: 0024 cost = 1.406147242
Epoch: 0025 cost = 1.339427710
Epoch: 0026 cost = 1.293059349
Epoch: 0027 cost = 1.250194669
Epoch: 0028 cost = 1.287502170
Epoch: 0029 cost = 1.170127630
Epoch: 0030 cost = 1.093732357
Epoch: 0031 cost = 1.168360472
Epoch: 0032 cost = 1.099991202
Epoch: 0033 cost = 1.015136480
Epoch: 0034 cost = 1.105043411
Epoch: 0035 cost = 1.122096300
Epoch: 0036 cost = 1.163351536
Epoch: 0037 cost = 1.203159332
Epoch: 0038 cost = 1.169082522
Epoch: 0039 cost = 1.148641229
Epoch: 0040 cost = 1.175602913
Epoch: 0041 cost = 1.131739974
Epoch: 0042 cost = 1.119367719
Epoch: 0043 cost = 1.058199644
Epoch: 0044 cost = 1.034004211
Epoch: 0045 cost = 0.999652982
Learning finished

In [202]:
submit = pd.read_csv('/kaggle/input/city-commercialchange-analysis/submit.csv')
submit

    ID  Label
0    0      0
1    1      0
2    2      0
3    3      0
4    4      0
..  ..    ...
57  57      0
58  58      0
59  59      0
60  60      0
61  61      0

[62 rows x 2 columns]

In [203]:
id=np.array([i for i in range(62)]).reshape(-1,1)
prediction=prediction.reshape(-1,1)

result=np.hstack([id, prediction])
df=pd.DataFrame(result, columns=['ID','Label'])
df.to_csv('baseline.csv', index=False, header=True)

result

array([[ 0,  3],
       [ 1,  0],
       [ 2,  0],
       [ 3,  3],
       [ 4,  3],
       [ 5,  0],
       [ 6,  0],
       [ 7,  3],
       [ 8,  3],
       [ 9,  0],
       [10,  0],
       [11,  3],
       [12,  0],
       [13,  0],
       [14,  3],
       [15,  0],
       [16,  3],
       [17,  0],
       [18,  3],
       [19,  3],
       [20,  0],
       [21,  0],
       [22,  3],
       [23,  3],
       [24,  0],
       [25,  3],
       [26,  3],
       [27,  3],
       [28,  0],
       [29,  0],
       [30,  3],
       [31,  3],
       [32,  0],
       [33,  3],
       [34,  0],
       [35,  3],
       [36,  3],
       [37,  3],
       [38,  3],
       [39,  3],
       [40,  3],
       [41,  3],
       [42,  0],
       [43,  3],
       [44,  3],
       [45,  3],
       [46,  3],
       [47,  3],
       [48,  3],
       [49,  3],
       [50,  3],
       [51,  0],
       [52,  3],
       [53,  3],
       [54,  3],
       [55,  3],
       [56,  3],
       [57,  3],
       [58,  0],
       [59,  3],
       [60,  3],
       [61,  0]])